### PR TITLE
Merge of alternate V0 Bed Wago Mount

### PR DESCRIPTION
**Pull request by NA411**
* [x] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [x] Folders names MUST NOT contain spaces. If possible, make sure file names also 
    do not contain any spaces.
  * [x] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [x] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [x] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [x] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [x] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [x] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [x] Submitted STL files are oriented and scaled properly for printing.
  * [x] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

#### Which mods/configurations/profiles are added by this PR?
QUAD 221-412 WAGO Holder

#### How was it tested? 
Printer and installed on two V0s

#### Any background context you want to provide?
Makes wiring the AC Bed easier and faster/convenient thermal fuse installation or replacement

#### Screenshots (if appropriate)
Images provided

#### Further notes
None

### CODE REVIEW

**Comment by deepfriedheroin** [comment]
@NA411 To properly merge this into the VoronUsers repo, we'll have to keep the files in the deepfriedheroin folder. From what I read into the comments, it was not that the file was a duplicate, in as much as it was a duplicate, taking up space in the readme, and folder structure.

Best bet to auto-merge with VoronUsers would be to stick it in [deepfriedheroin/v0_bed_wagos](https://github.com/deepfriedheroin/VoronUsers/tree/master/printer_mods/deepfriedheroin/v0_bed_wagos), add your step/stl/ images and update the existing readme to credit yourself and include your images. I'm pretty sure I can just push that when I merge.

I'm attempting to get this sorted, so we have a VoronUsers/dupes repo, somewhere. Not sure if that's gonna happen, though. 

I know this whole process has been a pain in the ass, especially when you're just trying to give back to the community. We whites and blues just don't have much say in how things work, and that's, probably, actually, a good thing.

I would be happy to merge, with your permission, and make the changes myself. 

Let me know what you decide. 

Starting 12-31-20, I will be back on discord. Same username. Feel free to ping or DM, to discuss.

**Comment by NA411** [comment]
@deepfriedheroin If that's the fastest, and proper way to to get everything merged, then I don't see an issue. 

Like you said, I just want to share my cool idea with the rest of the community. It's annoying that this process has taken this long, and been so involved. 

I'm still learning how to do things on GitHub, but I though that the pull request I did was on your repo and things would merge there and then to the main VoronUsers repo, but since you've volunteered to take the responsibility of merging... Please go ahead and make all of the necessary changes.

Let me know if there's anything else you need from me, and thanks for the help.

**Comment by deepfriedheroin** [comment]
👍 

I'll get to the merge tomorrow morning.

**Comment by deepfriedheroin** [comment]
Request includes [this folder](https://github.com/deepfriedheroin/VoronUsers/tree/589b827c8d5627882dfd0b9d412e3d143bfb0831/printer_mods/NA411/V0_Under_Bed_WAGO_Mount). I think it was left over from the original attempt to push to VoronUsers.  

Please remove the folder, **credit yourself in the updated readme** and create a new pull request, using a named branch, instead of master. 

Sorry. such a pain in the ass, but I'll stay on top of it, this time.

**Pull request closed without merging**
